SlnSistemaLogistica/src/SistemaLogistica.Web/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaLogistica.Domain.DTO;
using SistemaLogistica.Domain.IServices;
using SistemaLogistica.Web.Models;

namespace SistemaLogistica.Web.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientService _service;
        private readonly IPersonService _personService;
        public ClientController(IClientService service, IPersonService personService)
        {
            _service = service;
            _personService = personService;
        }

        public async Task<IActionResult> Index()
        {
            return View(_service.FindAll());
        }
        
        public async Task<IActionResult> Details(int id)
        {
            return View(_service.FindAll()
                        .Where(c => c.id == id));
        }

        public IActionResult Create()
        {
            ViewData["personId"] = new SelectList(_personService.FindAll(), "id","name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("id, personId")] ClientDTO client)
        {
            if (ModelState.IsValid)
            {
                if(await _service.Save(client)>0)
                    return RedirectToAction(nameof(Index));
            }
            ViewData["personId"] = new SelectList(_personService.FindAll(), "id","name");
            return View(client);
        }

        public async Task<IActionResult> Edit(int id)
        {
            if(id == null)
            {
                return NotFound(); 
            }
            ViewData["personId"] = new SelectList(_personService.FindAll(), "id","name");
            return View(await _service.FindById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id, [Bind("id, personId")] ClientDTO client)
        {
            if (!(id == client.id)) 
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if(await _service.Save(client)>0)
                    return RedirectToAction(nameof(Index));
            }
            ViewData["personId"] = new SelectList(_personService.FindAll(), "id","name");
            return View(client);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int? id)
        {
            var retDel = new ReturnJsonDel
            {
                status = "success",
                code = "200"
            };

            try
            {
                if (await _service.Delete(id ?? 0) <= 0)
                {
                    retDel = new ReturnJsonDel
                    {
                        status = "error",
                        code = "400"
                    };
                }
            }
            catch (Exception ex)
            {
                retDel = new ReturnJsonDel
                {
                    status = ex.Message,
                    code = "500"
                };
                throw;
            }
            return Json(retDel);
        }
    }
}

SlnSistemaLogistica/src/SistemaLogistica.Web/Controllers/InOutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaLogistica.Domain.DTO;
using SistemaLogistica.Domain.IServices;
using SistemaLogistica.Web.Models;

namespace SistemaLogistica.Web.Controllers
{
    public class InOutController : Controller
    {
        private readonly IInOutService _service;
        private readonly IProductService _productService;
        private readonly IClientService _clientService;
        public InOutController(IInOutService service, IProductService productService, IClientService clientService)
        {
            _service = service;
            _productService = productService;
            _clientService = clientService;
        }

        public async Task<IActionResult> Index()
        {
            return View(_service.FindAll());
        }
        
        public async Task<IActionResult> Details(int id)
        {
            return View(_service.FindAll()
                        .Where(i => i.id == id));
        }

        public IActionResult Create()
        {
            ViewData["productId"] = new SelectList(_productService.FindAll(), "id", "name");
            ViewData["clientId"] = new SelectList(_clientService.FindAll(), "id", "person.name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("id, inOrOut, time, productId, quantity, userName, clientId")] InOutDTO inOut)
        {
            if(ModelState.IsValid)
            {
                if(await _service.Save(inOut) > 0)
                    return RedirectToAction(nameof(Index));
            }
            return View(inOut);
        }
        public async Task<IActionResult> Edit(int id)
        {
            if(id == null)
            {
                return NotFound();
            }
            ViewData["productId"] = new SelectList(_productService.FindAll(), "id", "name");
            ViewData["clientId"] = new SelectList(_clientService.FindAll(), "id", "person.name");
            return View(await _service.FindById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id,[Bind("id, inOrOut, time, productId, quantity, userName, clientId")] InOutDTO inOut)
        {
            if(!(id == inOut.id)) 
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (await _service.Save(inOut) > 0)
                    return RedirectToAction(nameof(Index));
            }
            return View(inOut);
        }
        [HttpPost]
        public async Task<JsonResult> Delete(int? id)
        {
            var retDel = new ReturnJsonDel
            {
                status = "Success",
                code = "200"
            };

            try
            {
                if (await _service.Delete(id ?? 0) <= 0)
                {
                    retDel = new ReturnJsonDel
                    {
                        status = "Error",
                        code = "400"
                    };
                }
            }
            catch (Exception ex)
            {

                retDel = new ReturnJsonDel
                {
                    status = ex.Message,
                    code = "500"
                };
            }
            return Json(retDel);
        }
    }
}

SlnSistemaLogistica/src/SistemaLogistica.Web/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaLogistica.Domain.DTO;
using SistemaLogistica.Domain.IServices;
using SistemaLogistica.Web.Models;

namespace SistemaLogistica.Web.Controllers
{
    public class PersonController : Controller
    {
        private readonly IPersonService _service;

        public PersonController(IPersonService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            return View(_service.FindAll());
        } 
        
        public async Task<IActionResult> Details(int id)
        {
            return View(_service.FindAll()
                        .Where(p => p.id == id));
        }

        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create([Bind("id, name, cep, country, uf, city, neighbourhood, street, number")] PersonDTO person)
        {
            if (ModelState.IsValid)
            {
                if (await _service.Save(person) > 0)
                    return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        public async Task<IActionResult> Edit(int id)
        {
            if(id == null)
            {
                return NotFound();
            }
            return View(await _service.FindById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id, [Bind("id, name, cep, country, uf, city, neighbourhood, street, number")]PersonDTO person)
        {
            if (!(id == person.id)) 
            {
                return NotFound();
            }
            if(ModelState.IsValid)
            {
                if(await _service.Save(person) > 0) 
                    return RedirectToAction(nameof(Index));
            }
            return View(person);
        }
        [HttpPost]
        public async Task<JsonResult> Delete(int? id)
        {
            var retDel = new ReturnJsonDel
            {
                status = "Success",
                code = "200"
            };

            try
            {
                if (await _service.Delete(id ?? 0) <= 0)
                {
                    retDel = new ReturnJsonDel
                    {
                        status = "Error",
                        code = "400"
                    };
                }
            }
            catch(Exception ex)
            {
                retDel = new ReturnJsonDel
                {
                    status = ex.Message,
                    code = "500"
                };
            }
            return Json(retDel);
        }
    }
}

SlnSistemaLogistica/src/SistemaLogistica.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaLogistica.Domain.DTO;
using SistemaLogistica.Domain.IServices;
using SistemaLogistica.Web.Models;
using SistemaLogistica.Web.Models.DTO;

namespace SistemaLogistica.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _service;
        private readonly ICategoryService _categoryService;
        private readonly IFornecedorService _fornecedorService;
        public ProductController(IProductService service, ICategoryService categoryService, IFornecedorService fornecedorService)
        {
            _service = service;
            _categoryService = categoryService;
            _fornecedorService = fornecedorService;
        }

        public async Task<IActionResult> Index()
        {
            return View(_service.FindAll());
        }
        
        public async Task<IActionResult> Details(int id)
        {
            return View(_service.FindAll()
                        .Where(p => p.id == id));
        }

        public IActionResult Create()
        {
            ViewData["fornecedorId"] = new SelectList(_fornecedorService.FindAll(), "id", "person.name");
            ViewData["categoryId"] = new SelectList(_categoryService.FindAll(), "id", "name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("id, name, fornecedorId, quantityStock, quantityMinimun, image, categoryId")] ProductDTO product)
        {
            if (ModelState.IsValid)
            {
                if (await _service.Save(product) > 0)
                    return RedirectToAction(nameof(Index));
            }
            ViewData["fornecedorId"] = new SelectList(_fornecedorService.FindAll(), "id", "person.name");
            ViewData["categoryId"] = new SelectList(_categoryService.FindAll(), "id", "name");
            return View(product);
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewData["fornecedorId"] = new SelectList(_fornecedorService.FindAll(), "id", "person.name");
            ViewData["categoryId"] = new SelectList(_categoryService.FindAll(), "id", "name");
            return View(await _service.FindById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id, [Bind("id, name, fornecedorId, quantityStock, quantityMinimun, image, categoryId")] ProductDTO product)
        {
            if (!(id == product.id))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (await _service.Save(product) > 0)
                    return RedirectToAction(nameof(Index));
            }
            ViewData["fornecedorId"] = new SelectList(_fornecedorService.FindAll(), "id", "person.name");
            ViewData["categoryId"] = new SelectList(_categoryService.FindAll(), "id", "name");
            return View(product);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int? id)
        {
            var retDel = new ReturnJsonDel
            {
                status = "success",
                code = "200"
            };

            try
            {
                if (await _service.Delete(id ?? 0) <= 0)
                {
                    retDel = new ReturnJsonDel
                    {
                        status = "Error",
                        code = "400"
                    };
                }
            }
            catch (Exception ex)
            {
                retDel = new ReturnJsonDel
                {
                    status = ex.Message,
                    code = "500"
                };
            }
            return Json(retDel);
        }

        public IActionResult ImagePost(int id)
        {
            ImageFieldProduct productModel = new ImageFieldProduct();
            if(id != null)
            {
                productModel.idProduct = id;
            }
            return View(productModel);
        }
        [HttpPost]
        public async Task<IActionResult> ImagePost(int idProduct, List<IFormFile> imageProduct)
        {
            try
            {
                if(idProduct == null)
                {
                    ViewBag.Message = $"O Id é null";
                    return View(new ImageFieldProduct() { idProduct = idProduct });
                }

                var file = imageProduct.FirstOrDefault();
                var fileName = $"{idProduct}_{file.FileName}";
                string path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot//Uploads",fileName);
            
                if (await _service.SaveFile(idProduct,fileName) > 0)
                {
                    var stream = new FileStream(path, FileMode.Create);
                    await file.CopyToAsync(stream);
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Message = $"Não foi possível salvar o arquivo: {path}";
                return View(new ImageFieldProduct() { idProduct = idProduct , imageProduct = fileName});
            }
            catch (Exception ex)
            {

                ViewBag.Message = $"Error: {ex.Message}";
            }
            return View();
        }
    }
}

SlnSistemaLogistica/src/SistemaLogistica.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaLogistica.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaLogistica.Web.styles.css" asp-append-version="true" />
</head>
<body class="bg-warning">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-info border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Drink's Estoque</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Pessoas
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li> <a class="dropdown-item" asp-area="" asp-controller="Person" asp-action="Index">Pessoa</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedor</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Client" asp-action="Index">Cliente</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Produto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InOut" asp-action="Index">Saída/Entrada</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-info">
        <div class="container">
            &copy; 2023 - Drink's Estoque - Mateus Eduardo Falk
        </div>
    </footer>

    <!-- Messages using Toasts Component -->
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <strong class="me-auto">Drink's Estoque - <span id="toast-origin"></span></strong>
                <small id="toast-time">11:00</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body" id="toast-body">
                Hello, world! This is a toast message.
            </div>
        </div>
    </div>
    <!-- Messages using Toasts Component -->
    <div class="modal fade" id="msgModal" tabindex="-1" aria-labelledby="msgModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="msgModalLabel">Sistema De Logistica - Message</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div id="modal-body" class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button id="btnModalCallback" type="button" class="btn btn-primary">Ok</button>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>